include $(TOPDIR)/build/config.mk

PREFIX_DIR	= $(CFG_PREFIX_DIR)
BIN_DIR		= $(CFG_ROOT_DIR)/bin
SBIN_DIR	= $(CFG_ROOT_DIR)/sbin
LIBEXE_CDIR	= $(CFG_ROOT_DIR)/libexec
SYSCONF_DIR	= $(CFG_ROOT_DIR)/etc
SHARESTATE_DIR	= $(CFG_ROOT_DIR)/com
LOCALSTATE_DIR	= $(CFG_ROOT_DIR)/var
LIB_DIR		= $(CFG_ROOT_DIR)/lib
INCLUDE_DIR	= $(CFG_ROOT_DIR)/include
OLDINCLUDE_DIR	= /usr/include
PYTHON_LIBDIR	= $(CFG_ROOT_DIR)/lib/python2.7/site-packages

DATAROOT_DIR	= $(CFG_ROOT_DIR)/share
DATA_DIR	= $(DATAROOT_DIR)
INFO_DIR	= $(DATAROOT_DIR)/info
LOCALE_DIR	= $(DATAROOT_DIR)/locale
MAN_DIR		= $(DATAROOT_DIR)/man
DOC_DIR		= $(DATAROOT_DIR)/doc/$(PROG)
HTML_DIR	= $(DOC_DIR)
DVI_DIR		= $(DOC_DIR)
PDF_DIR		= $(DOC_DIR)
PS_DIR		= $(DOC_DIR)


HOSTMK		= make
MAKE		= $(HOSTMK)

HOSTCC		= gcc
HOSTCPP		= cpp
HOSTCXX		= g++
HOSTCXXCPP	= cpp -x c++
HOSTYACC	= yacc
HOSTLD		= ld
HOSTLDSHARED	= gcc -shared
HOSTNM		= nm
HOSTAR		= ar
HOSTSTRIP	= strip
HOSTRANLIB	= ranlib

CC		= $(CROSS_COMPILE)gcc
CPP		= $(CROSS_COMPILE)cpp
CXX		= $(CROSS_COMPILE)g++
CXXCPP		= $(CROSS_COMPILE)cpp -x c++
YACC		= $(CROSS_COMPILE)yacc
LD		= $(CROSS_COMPILE)ld
LDSHARED	= $(CROSS_COMPILE)gcc -shared
NM		= $(CROSS_COMPILE)nm
AR		= $(CROSS_COMPILE)ar
STRIP		= $(CROSS_COMPILE)strip
RANLIB		= $(CROSS_COMPILE)ranlib

CFLAGS		= -I$(TOPDIR)/include $(EXTRA_CFLAGS)
CPPFLAGS	= 
CXXFLAGS	= -I$(TOPDIR)/include $(EXTRA_CXXFLAGS)
YFLAGS		= $(EXTRA_YFLAGS)
LDFLAGS		= $(EXTRA_LDFLAGS)
LIBS		= $(EXTRA_LIBS)

