CMAKE_CMD		:= cmake
CMAKE_C_COMPILER	:= $(CC)
CMAKE_CXX_COMPILER	:= $(CXX)
CMAKE_C_COMPILER_ARG1	:=
CMAKE_CXX_COMPILER_ARG1	:=
CMAKE_AR		:= $(shell which $(AR))
CMAKE_RANLIB		:= $(shell which $(RANLIB))

CMAKE_SOURCE_DIR	:= .
CMAKE_PREFIX		:= /

CMAKE_VARS = $(MAKE_VARS) \

CMAKE_ARGS = \
	-DCMAKE_SYSTEM_NAME=Linux \
	-DCMAKE_SYSTEM_VERSION=1 \
	-DCMAKE_SYSTEM_PROCESSOR=$(ARCH) \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" \
	-DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" \
	-DCMAKE_C_COMPILER="$(CMAKE_C_COMPILER)" \
	-DCMAKE_C_COMPILER_ARG1="$(CMAKE_C_COMPILER_ARG1)" \
	-DCMAKE_CXX_COMPILER="$(CMAKE_CXX_COMPILER)" \
	-DCMAKE_CXX_COMPILER_ARG1="$(CMAKE_CXX_COMPILER_ARG1)" \
	-DCMAKE_EXE_LINKER_FLAGS:STRING="$(LDFLAGS)" \
	-DCMAKE_MODULE_LINKER_FLAGS:STRING="$(LDFLAGS)" \
	-DCMAKE_SHARED_LINKER_FLAGS:STRING="$(LDFLAGS)" \
	-DCMAKE_AR="$(CMAKE_AR)" \
	-DCMAKE_RANLIB="$(CMAKE_RANLIB)" \
	-DCMAKE_FIND_ROOT_PATH="$(CFG_STAGE_DIR);$(TOOLCHAIN_DIR)" \
	-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH \
	-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
	-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
	-DCMAKE_STRIP=: \
	-DCMAKE_INSTALL_PREFIX=$(CMAKE_PREFIX) \
	-DDL_LIBRARY=$(CFG_STAGE_DIR) \
	-DCMAKE_PREFIX_PATH=$(CFG_STAGE_DIR) \
	$(CMAKE_OPTIONS) \

define Build/Configure/Default
	( cd $(PKG_BUILD_DIR); \
		$(CMAKE_VARS) \
		$(CMAKE_CMD) \
		$(CMAKE_ARGS); \
	)
endef
